#!/usr/bin/env python3
"""Generate Launch and Management documentation.

This script creates docs/LAUNCH_MANAGEMENT.md by reading README.md,
requirements.txt, and the command line help of soul_link.py.
Run it whenever these sources change to keep the documentation up to date.
"""
from pathlib import Path
import subprocess

repo_root = Path(__file__).resolve().parents[1]
readme = repo_root / "README.md"
requirements = repo_root / "requirements.txt"
soul_link = repo_root / "soul_link.py"

readme_text = readme.read_text()
requirements_text = requirements.read_text().strip()

help_output = subprocess.check_output(["python3", str(soul_link), "--help"], text=True)

doc_path = repo_root / "docs" / "LAUNCH_MANAGEMENT.md"

doc = f"""# Launch and Management Guide

This file is auto-generated by `python docs/generate_launch_doc.py`.

## Requirements

```
{requirements_text}
```

## Overview

{readme_text}

## Command-line Usage of `soul_link.py`

```
{help_output.strip()}
```
"""

doc_path.write_text(doc)
print(f"Wrote {doc_path}")
